### ISSUE TITLE
Error when I try to connect with the code exemple (Laravel 5)

### ISSUE THREAD

**Issue by shinigami35** [RobinvdVleuten/php-nntp#11]
Hi,

My name is Adrien, and I have some problems with your library PHP-NNTP. I am using your library with the framework Laravel 5. 

When I use your library, I have the same error all time : 'Invalid response given: response string should be terminated by &#92;r&#92;n'. I do not know why I have this error.

I am using you exemple to connect with the server of php news. I do a copy/paste with your exemple code but I always have this error.

Can you explain me with i have this error all time ?

Regards Adrien.

My code is : 

```php

//Code in my controller

/**
**  This is the route when I try to call my function
**  Route::get('/test', 'MainController@index');
**/

public function index()
{
    $connection = new Connection('news.php.net', 119);
    $client = new Client($connection);

    $client->connect();  //Error here 

    $command = $client->overviewFormat();
    $overviewFormat = $command->getResult();

    $command = $client->group('php.doc');
    $group = $command->getResult();

    $command = $client->xover($group['first'], $group['first'] + 100, $overviewFormat);
    $articles = $command->getResult();

    dd($articles); //laravel var_dump and die

    $client->disconnect();
    return false;
}
```

Best regards

**Comment by RobinvdVleuten** [comment]
Hi Adrien, 

Can you give a dump of the buffer where the response is created from on this line?
https://github.com/RobinvdVleuten/php-nntp/blob/master/src/Connection/Connection.php#L157

**Comment by shinigami35** [comment]
The buffer is empty, I have nothing in and i do not understand why the buffer is empty.

**Comment by RobinvdVleuten** [comment]
Maybe something went wrong with the socket interaction in the Connection class. I can't help you with only this information so you have to try to debug the Connection class yourself.

**Comment by shinigami35** [comment]
Ok, I will try to understand, but it is strange that the socket interaction doesn't work.

**Comment by JoeDawson** [comment]
I also get the same with the example in the README, @shinigami35 did you manage to resolve this?

**Comment by robinvdvleuten** [comment]
@JoeDawson can you confirm that the issue is fixed in the master branch? Then I can create a new release (0.8) for it.

**Comment by JoeDawson** [comment]
Yeah the issue is fixed in the master branch, the code example in the
README works 😊

**Comment by robinvdvleuten** [comment]
@JoeDawson I've bumped the version to 0.8. If you find any issues please let me know or even better submit a PR to improve the lib 😄

**Comment by JoeDawson** [comment]
Working as I hoped @robinvdvleuten 👍
