### ISSUE TITLE
Ouch what happened?

### ISSUE THREAD

**Issue by warlord0** [robinvdvleuten/php-nntp#21]
My project just upgraded to 0.7 and now times out on trying to connect to the news server. I even switched it back to plain 119 and not ssl to see if it was an issue there. No luck :(

I can access the server and port and see it's open using nmap.

```
 [ErrorException]
  stream_socket_client(): unable to connect to tcp://newsreader60.eweka.nl:11
  9 (Connection timed out)
```

and the laravel log:
```
[2016-02-16 21:53:53] local.ERROR: exception 'ErrorException' with message 'stream_socket_client(): unable to connect to tcp://newsreader60.eweka.nl:119 (Connection timed out)' in /var/www/Nassau/vendor/rvdv/nntp/src/Socket/Socket.php:46
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'stream_socket_c...', '/var/www/Nassau...', 46, Array)
#1 /var/www/Nassau/vendor/rvdv/nntp/src/Socket/Socket.php(46): stream_socket_client('tcp://newsreade...', 110, 'Connection time...', 0, 4)
#2 /var/www/Nassau/vendor/rvdv/nntp/src/Connection/Connection.php(81): Rvdv\Nntp\Socket\Socket->connect('tcp://newsreade...', NULL)
#3 /var/www/Nassau/vendor/rvdv/nntp/src/Client.php(54): Rvdv\Nntp\Connection\Connection->connect()
#4 /var/www/Nassau/vendor/rvdv/nntp/src/Client.php(94): Rvdv\Nntp\Client->connect()
```

```
Starting Nmap 6.47 ( http://nmap.org ) at 2016-02-16 22:01 GMT
Nmap scan report for newsreader60.eweka.nl (81.171.92.205)
Host is up (0.035s latency).
PORT    STATE SERVICE
119/tcp open  nntp
563/tcp open  snews

Nmap done: 1 IP address (1 host up) scanned in 0.11 seconds
```

**Comment by warlord0** [comment]
If I pass a $timeout as 60 it seems to hang forever. It establishes a connection but doesn't proceed.

```
tcp        0      0 192.168.0.148:42495     81.171.92.205:119       ESTABLISHED
```

**Comment by robinvdvleuten** [comment]
@warlord0 yeah some things went wrong when I moved to an external socket library without proper testing. It should be fixed now by moving the whole stream_socket_* functionality to a separate class for better unit testing. In combination with a forced update + git tags, the whole thing broke. 

Can you try it again to install version 0.7.0? The correct hash should be 4c70a1b162b929d1cc044b938639dced94426148. 

When I try to connect with this commit, I get an authentication required response;

```php
$connection = new Connection('newsreader60.eweka.nl', 119, false, 15);
$client = new Client($connection);

$client->connect();
```

The timeout argument defaults to null so it falls back to the globally configured timeout settings in php.ini. You need to set it explicitly to a sensible value for your project.

Sorry about all this, this was one in the category "move fast and break things" ;)

**Comment by warlord0** [comment]
Phew. Glad it's not me. :+1: 

I like the idea, just the implementation has killed me ;) You should get prompted for authentication as that's normal behaviour.

My problem now is trying to figure out how to github it into my project. Currently just using composer and it's not seeing any update. I guess it won't until you put it into packagist? You'll have to forgive me I'm a little new to this version control arena.

**Comment by robinvdvleuten** [comment]
No worries! The correct version is already on packagist, but you probably already have the previous version installed through composer. So try to remove the _vendor/rvdv/nntp_ directory and run composer update again, that should do the trick.

**Comment by warlord0** [comment]
Something's still giving me problems.

I see it get passed the connect stage, but then when I issue a command it stalls.
This is how I'm using it:
```
    private function connect() {
        $this->connection = new Connection($this->server, $this->port, $this->secure, **15**);
        $this->client = new Client($this->connection);
        
        if ($this->username !== **null**) { **// Not null so it does authenticate**
            $this->client->connectAndAuthenticate($this->username, $this->password);
        } else {
            $this->client->connect();
        }
    }
    private function disconnect() {
        $this->client->disconnect();
    }
```

and in the later functions:
```
$this->connect(); 
echo("x\n");

$command = $this->client->overviewFormat();
echo("y\n");
$overviewFormat = $command->getResult();

$command = $this->client->group($newsgroup->name);
echo("z\n");
$group = $command->getResult();
```

I get to see "x", but then no further.

**Comment by robinvdvleuten** [comment]
@warlord0 If I run the example, it runs as expected;

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Rvdv\Nntp\Connection\Connection;
use Rvdv\Nntp\Client;

$connection = new Connection('news.php.net', 119, false, 15);
$client = new Client($connection);

$client->connect();

$command = $client->overviewFormat();
$overviewFormat = $command->getResult();

var_dump($overviewFormat);

$command = $client->group('php.doc');
$group = $command->getResult();

var_dump($group);

$command = $client->xover($group['first'], $group['first'] + 100, $overviewFormat);
$articles = $command->getResult();

// Process the articles further...
var_dump($articles);

$client->disconnect();
```

Can you please check it with the php nntp server?

**Comment by warlord0** [comment]
I spent the day yesterday kicking this about trying to resolve it with no luck :( In the end I rolled back to 6.0 and it runs like a charm.

Thanks for your efforts, by the way. It is appreciated.

So this morning I edited the example above - had to change a few lines to make it work with my server and ran it under version 6.0. It ran fine and I got headers.

```
require_once '../../vendor/autoload.php';

use Rvdv\Nntp\Connection\Connection;
use Rvdv\Nntp\Client;

$connection = new Connection('newsreader60.eweka.nl', 119, false, 15);
$client = new Client($connection);

$username = 'xxxxxx';
$password = 'xxxxxx';

$client->connectAndAuthenticate($username, $password);
...
```
Some headers as proof
```
  [96]=>
  array(9) {
    ["number"]=>
    string(2) "98"
    ["subject"]=>
    string(127) "cvs: phpdoc /en/reference/apache/functions apache-request-headers.xml apache-response-headers.xml getallheaders.xml virtual.xml"
    ["from"]=>
    string(32) "thetaphi@php.net (Uwe Schindler)"
    ["date"]=>
    string(31) "Tue, 15 Jul 2003 17:59:36 -0000"
    ["message_id"]=>
    string(33) "<cvsthetaphi1058291976@cvsserver>"
    ["references"]=>
    string(0) ""
    ["bytes"]=>
    string(4) "7785"
    ["lines"]=>
    string(3) "163"
    ["xref"]=>
    string(24) "news.eweka.nl php.doc:98"
  }
```
Then I did a composer remove rvdv/nntp a clear cache and then a composer require rvdv/nntp to reinstall 7.0

After that I ran it and get nothing back from the server again :(
```
$ php socket.php
```
Hangs indefinitely.

**Comment by warlord0** [comment]
PS. I stuck in an echo after the  the connectAndAuthenticate and it gets there. So appears to be sticking at the $client->group() command.

**Comment by robinvdvleuten** [comment]
@warlord0 so I guess I've pinpointed the issue. The stream was previously read through fgets and I changed it after v0.6.0 to freads. Can you try to install version "1.0.*@dev" for now to check if it fixes it for you?

**Comment by warlord0** [comment]
Woohoo, looks like you managed to fix it :+1: Well as far as I can tell. I ran the example and got an error about the 4th argument passed being an integer - which was the timeout, when it was expecting a Socket. So I dropped that and boom - I got headers!
```
  [100]=>
  array(9) {
    ["number"]=>
    string(3) "102"
    ["subject"]=>
    string(74) "#24672 [NEW]: Search Documentation - Function list does not work correctly"
    ["from"]=>
    string(50) "phpdoc@lists.php.net (S Dot Pfalz At Teles Dot De)"
    ["date"]=>
    string(26) "16 Jul 2003 07:51:29 -0000"
    ["message_id"]=>
    string(24) "<bug-24672@bugs.php.net>"
    ["references"]=>
    string(0) ""
    ["bytes"]=>
    string(4) "3169"
    ["lines"]=>
    string(2) "52"
    ["xref"]=>
    string(25) "news.eweka.nl php.doc:102"
  }
```

**Comment by robinvdvleuten** [comment]
Cool! I'll create some additional unit tests for the socket class and then create a new release afterwards. Sorry for all the inconveniences ;)

**Comment by warlord0** [comment]
No problem. Thanks for sorting it.

**Comment by warlord0** [comment]
PS: I discovered by accident that you also seem to have sorted the SSL Wildcard issue.

In my project it's still set to secure on port 563 and it's working.
```
tcp        0      0 192.168.0.148:60907     81.171.92.205:563       ESTABLISHED
```
