### ISSUE TITLE
listGroups

### ISSUE THREAD

**Issue by DonCarlosGraz** [robinvdvleuten/php-nntp#29]
I'm not sure (at least at my private news server this issue exists), but for me the listGroups function does not work, because the called response method is 'onInformationFollows' and not 'onListFollows'.

is this a bug or only an issue on the news server?

**Comment by robinvdvleuten** [comment]
I guess that's a bug then! I've checked the corresponding [RFC](https://www.ietf.org/rfc/rfc2980.txt) and it indeed returns an `215 Information Follows` response. Thanks for reporting!
