### ISSUE TITLE
How can I use the Article command?

### ISSUE THREAD

**Issue by JoeDawson** [robinvdvleuten/php-nntp#30]
Hey!

Do you have any documentation on how to use the Article command?

Thanks

**Comment by robinvdvleuten** [comment]
The Article command lacks a bit of documentation I'm afraid. You can check out the test case of the command (https://github.com/robinvdvleuten/php-nntp/blob/master/tests/Command/ArticleCommandTest.php#L111) to see that you can pass an article identifier to get an article;

```php
$client->sendCommand(new ArticleCommand('[identifier of article]'));
``` 

Feel free to send any PR regarding improvements on the library!

**Comment by JoeDawson** [comment]
Thanks @robinvdvleuten.
