### ISSUE TITLE
Add license header to each file

### ISSUE THREAD

**Issue by robinvdvleuten** [robinvdvleuten/php-nntp#6]
Add license header to each file

**Comment by Anahkiasen** [comment]
Can use [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) for that, it has a `header_comment` fixer, that's what I use.

**Comment by robinvdvleuten** [comment]
Thanks for the suggestion! Didn't know that :+1:

**Comment by Anahkiasen** [comment]
[example](https://github.com/rocketeers/rocketeer/blob/master/.php_cs#L8)
